version: '3.8'
services:
  postgres:
    image: postgres
    container_name: fabric_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fabric_gateway_db
    ports:
      - '5434:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data