name: Restrict PR to master from develop

on:
  pull_request:
    branches:
      - master

jobs:
  restrict-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        run: |
          if [ "${{ github.event.pull_request.head.ref }}" != "develop" ]; then
            echo "Pull requests to master must come from the develop branch."
            exit 1
          fi
